### ISSUE TITLE
When sending a transaction fails, entered information gets cleared

### ISSUE THREAD

**Issue by thomasoehri** [NemProject/NEMiOSApp#231]
When i try to send a new transaction and sending somehow fails, all information i entered gets cleared which is super annoying. Nobody reckons witch a failure while writing the transaction and therefore doesn't copy for example the message he wrote - when sending the transaction fails one has to write it again. There is absolutely no reason to clear all entered information on failure, the user should be able to just try again.

NDXRV4-767UOX-C2CY3Y-IRLFMB-TWIXXS-V7GQYO-WELC

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 39

**Comment by Mehbsl** [comment]
Not fixed, all entered information still gets cleared when an error occurs.

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 40

**Comment by thomasoehri** [comment]
This issue is still not fixed with build 40.
I made this video showcasing what i mean: https://youtu.be/lf1qQH3JG3Q

**Comment by jabo38** [comment]
not resolved.  please see video.

**Comment by LyubomirDominik** [comment]
Remove accounts from address book and reinstall app. And try again.
Account is broken, they was created in old versions or manually

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 41

**Comment by jabo38** [comment]
fixed
