### ISSUE TITLE
blue copy and paste dots linger

### ISSUE THREAD

**Issue by jabo38** [NemProject/NEMiOSApp#232]
If I go to copy and paste my private key, but then hit the back button, the blue dots used for highlighting when copying and pasting remain behind from panel to panel.

![image](https://cloud.githubusercontent.com/assets/10395907/15987002/6bdb6406-3054-11e6-9188-c7c7c2c988d6.png)

**Comment by Espo02** [comment]
Yes, I can reproduce it.

![photo-2016-06-11-21-23-16_2190](https://cloud.githubusercontent.com/assets/17567386/15987032/e52d1604-301a-11e6-93ec-3866ffd8e00a.PNG)

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 39

**Comment by Mehbsl** [comment]
Not fixed for me with build 39:

![img_2349 png](https://cloud.githubusercontent.com/assets/18571472/16046989/a6a8a37c-324e-11e6-9d9f-2e77efcff14d.jpeg)
![img_2348 png](https://cloud.githubusercontent.com/assets/18571472/16047035/d2977652-324e-11e6-804d-65b42be4dfcd.jpeg)

**Comment by Espo02** [comment]
I tried hard, but I could not reproduce it. 
Iphone 5S, NEMiOS2BETA39

**Comment by Mehbsl** [comment]
This issue is a result of issue #221. If #221 would get fixed, issues like these couldn't happen.

**Comment by jabo38** [comment]
Still exists.  Iphone 6 iOS 9.3.2

here is a video

https://app.box.com/s/zxr2z4qzr82gno8oqqq7l6gsev6gm4bx

**Comment by LyubomirDominik** [comment]
Try a lot but can not reproduce on Iphone 6 6s 5 5s

**Comment by LyubomirDominik** [comment]
Try to reproduce in Version 2 Buld 40

**Comment by jabo38** [comment]
not fixed

**Comment by LyubomirDominik** [comment]
Can not reproduce in Version 2 Build 40- 41. I can only suggest to reinstall app.

**Comment by jabo38** [comment]
deleted app. reinstalled app. problem is still there.  iphone 6, Version 2.0 Build 41, iOS 9.3.2

**Comment by LyubomirDominik** [comment]
Fixed in Version 2 Build 42. 

Also if you pass address for unknown account (for app) it will show localized error "UNKNOWN_ACCOUNT_ADDRESS" localization exist in app and google doc, but on in localization files provided for us.

**Comment by LyubomirDominik** [comment]
Try to reproduce in Version 2 Build 42. Can not reproduce.

**Comment by jabo38** [comment]
fixed
