### ISSUE TITLE
Adding contact through scanning Nano 'Share Account Info' QR = 'Couldn't Create Contact' on save.

### ISSUE THREAD

**Issue by csleary** [NemProject/NEMiOSApp#284]
Bug I've come across that I can't find mentioned.

Nano wallet: 1.3.12
iOS Wallet: 1.1.2 Build 1

Trying to scan the address info in Nano with the iOS wallet, in order to save it as a contact, results in the message: "Info: Couldn't Create Contact."

The account appears to have been scanned correctly, as it populates the contact fields with first name and the correct address, but it cannot be saved.

**Comment by takecian** [comment]
@csleary how often does this error occur? Every time?
If not, can you attach QR code which occurs error?

**Comment by csleary** [comment]
Hi Takeshi! Actually, I get the same error trying so save a contact manually, so I think the issue is during the attempt to save the contact, rather than the scanning (the scan reads and displays the data correctly). But yes, it occurs every time. I can't save any contacts.

**Comment by takecian** [comment]
Hmm..I tried saving contacts by scanning QR code with latest source code, it worked.
I tried adding contacts by putting name and address manually, it also worked.

Is it possible to share QR code you tested?

**Comment by csleary** [comment]
The only reason I can think this might have happened is after denying initial access to my phone contacts when running the app for the first time. Might that be the issue? Perhaps something that needed to be initialised relied on the user accepting access to phone contacts first?

The QR code data looked like this (address removed for privacy):

`{"v":2,"type":1,"data":{"addr":"ABCDEABCDEABCDEABCDEABCDEABCDEABCDEABCDE","name":"Name"}}`

Like I say, it scanned the address info just fine, so I don't think that's the issue.

Aha -- I can make the app crash repeatedly if I try to search for contacts. I think this might be it. After not accepting contacts access/import the app might assume their existence, and then crashes when no existing contacts are found.

**Comment by csleary** [comment]
Yes, that seems to be the issue -- if the user has contact addresses switched off, then trying to add a contact will present the error message. I believe it would be more useful to remind the user that the app needs access to the contacts, and prompt a settings button.

Regardless of whether the app can access contacts or not, the app still crashes when you try to search for a non-existent user by clicking on the spyglass after typing it in.

Can you reproduce the error message and crashes using the above info with contact access turned off?

**Comment by takecian** [comment]
I could reproduce error message and crash if switching off contact address access.
I will try to fix it.

**Comment by csleary** [comment]
Great, thanks Takeshi!

Also, might be nice if the app checks contacts for a company name if there are no first and last names present, as at the moment companies are just shown as empty names in the NEM app.

If bug bounties are still on offer, here's my address:
NBCR2G-JL7VJF-3FKVI6-6SMZCG-4YBC6H-3BM2A6-LLTM
Much appreciated.

**Comment by takecian** [comment]
Actually I'm just a contributor, so i'm not sure about current bug bounties status..
Anyway i fixed this issue so create Pull Request.

**Comment by jabo38** [comment]
Problem still exists. 

Bounty Paid Transaction hash: 32a2711d62d53eeeac9f223e0c7757f88a6db55a10f0eaf7deb3958f9d6e6483

**Comment by takecian** [comment]
@jabo38 still exists? can you tell me detais?
